# Generated by Django 5.1.1 on 2024-09-28 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=150)),
                ('amount', models.FloatField()),
                ('description', models.CharField(max_length=250)),
            ],
        ),
    ]
