# Generated by Django 5.1.1 on 2024-09-28 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_expense_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='category',
        ),
    ]
