# Generated by Django 5.1.1 on 2024-10-02 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=150)),
                ('amount', models.FloatField()),
                ('description', models.CharField(max_length=250)),
                ('date', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RecurringExpense',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=250)),
                ('amount', models.FloatField()),
                ('category', models.CharField(max_length=150)),
                ('frequency', models.CharField(max_length=250)),
                ('date', models.CharField(max_length=100)),
            ],
        ),
    ]
